version: "3.3"

services:
  server:
    build: server/
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - /data/qr_codes:/data/qr_codes:rw
    restart: always
    ports:
      - "8082:8082"
    command: python3 ./server.py -u
